alias(
    name = "compile_commands",
    actual = "@wolfd_bazel_compile_commands//:generate_compile_commands",
)

alias(
	name = "scc",
	actual = "//tools/scc:scc"
)

alias(
    name = "lexer_fuzz",
    actual = "//fuzz:lexer_fuzz_test_run",
)

test_suite(
      name = "all",
      tests = ["//test:all"],
)
