
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/bonsthie/.nix-profile/bin/"
      - "/nix/var/nix/profiles/default/bin/"
      - "/tmp/.tmpqE99Mv/"
      - "/usr/lib/node_modules/@openai/codex/node_modules/@vscode/ripgrep/bin/"
      - "/usr/lib/jvm/default/bin/"
      - "/home/bonsthie/Documents/code/scc/build2/_deps/googletest-subbuild/.local/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/usr/bin/site_perl/"
      - "/usr/bin/vendor_perl/"
      - "/usr/bin/core_perl/"
      - "/bin/"
    searched_directories:
      - "/home/bonsthie/.nix-profile/bin/uname"
      - "/nix/var/nix/profiles/default/bin/uname"
      - "/tmp/.tmpqE99Mv/uname"
      - "/usr/lib/node_modules/@openai/codex/node_modules/@vscode/ripgrep/bin/uname"
      - "/usr/lib/jvm/default/bin/uname"
      - "/home/bonsthie/Documents/code/scc/build2/_deps/googletest-subbuild/.local/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/bonsthie/.nix-profile/bin"
        - "/nix/var/nix/profiles/default/bin"
        - "/tmp/.tmpqE99Mv"
        - "/usr/lib/node_modules/@openai/codex/node_modules/@vscode/ripgrep/bin"
        - "/usr/lib/jvm/default/bin"
        - "/home/bonsthie/.nix-profile/bin"
        - "/nix/var/nix/profiles/default/bin"
        - ".local/bin"
        - "/usr/lib/jvm/default/bin"
        - "/home/bonsthie/.nix-profile/bin"
        - "/nix/var/nix/profiles/default/bin"
        - ".local/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/usr/bin/site_perl"
        - "/usr/bin/vendor_perl"
        - "/usr/bin/core_perl"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.17.2-arch1-1 - x86_64
...
