load("//bazel:scc.bzl", "scc_lit_test")

package(default_visibility = ["//visibility:public"])

scc_lit_test(
    name = "driver",
    dir = "Driver",
    data = [
        "lit.cfg.py",
		"//tools/scc:scc"
	],
)

scc_lit_test(
    name = "cc1_driver",
    dir = "CC1Driver",
    data = [
        "lit.cfg.py",
		"//tools/scc:scc"
	],
)

scc_lit_test(
    name = "lex",
    dir = "Lex",
    data = [
        "lit.cfg.py",
        "//tools/scc:scc",
    ],
)

scc_lit_test(
    name = "parser",
    dir = "Parser",
    data = [
        "lit.cfg.py",
        "//tools/scc:scc",
    ],
)

test_suite(
    name = "lit",
    tests = [
		":cc1_driver_lit",
        ":driver_lit",
        ":lex_lit",
        ":parser_lit",
    ],
)
