load("//bazel:scc.bzl", "scc_cc_test", "scc_test_group")

package(default_visibility = ["//visibility:public"])

scc_cc_test(
    name = "adt",
    srcs = [
        "ADT/BaseVectorTest.cpp",
        "ADT/SmallVectorTest.cpp",
    ],
    deps = ["//lib/Allocator"],
)

scc_cc_test(
    name = "allocator",
    srcs = [
        "Allocator/BumpAllocatorTest.cpp",
        "Allocator/StackGrowAllocatorTest.cpp",
    ],
    deps = ["//lib/Allocator"],
)

scc_cc_test(
    name = "ast",
    srcs = ["AST/TypeTests.cpp"],
    deps = ["//lib/AST"],
)

scc_cc_test(
    name = "error",
    srcs = ["Error/ErrorManagerTest.cpp"],
    deps = ["//lib/Error"],
)

scc_cc_test(
    name = "file-manager",
    srcs = [
        "FileManager/FMUtils.h",
        "FileManager/FMUtils.cpp",
        "FileManager/FileFinderTest.cpp",
        "FileManager/FileManagerTest.cpp",
        "FileManager/FileTest.cpp",
    ],
    deps = ["//lib/FileManager"],
    includes = ["FileManager"],
)

scc_cc_test(
    name = "lex",
    srcs = ["Lex/FileLexerTests.cpp"],
    deps = [
        "//lib/Allocator",
        "//lib/Lex",
    ],
)

scc_cc_test(
    name = "option",
    srcs = ["Option/OptionTableTest.cpp"],
    deps = ["//lib/Option"],
)

scc_cc_test(
    name = "preprocessor",
    srcs = ["PreProcessor/PreProcessorTest.cpp"],
    deps = ["//lib/PreProcessor"],
)

scc_cc_test(
    name = "sema",
    srcs = ["Sema/ScopeTests.cpp"],
    deps = ["//lib/Sema"],
)

scc_cc_test(
    name = "string",
    srcs = ["String/StringHelpersTest.cpp"],
    deps = ["//lib/Allocator"],
)

scc_cc_test(
    name = "token",
    srcs = ["Token/TokenTest.cpp"],
    deps = ["//lib/Token"],
)

scc_test_group(
    name = "all",
    tests = [
        ":adt",
        ":allocator",
        ":ast",
        ":error",
        ":file-manager",
        ":lex",
        ":option",
        ":preprocessor",
        ":sema",
        ":string",
        ":token",
    ],
)
